# Generated by Django 4.2.8 on 2023-12-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Planned'), ('R', 'Released'), ('C', 'Close'), ('F', 'Canceled')], default='P', max_length=1)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('salesOrder', models.PositiveIntegerField(default=1)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('docno', models.PositiveIntegerField(default=1, unique=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Production Order',
                'verbose_name_plural': 'Production Order',
            },
        ),
        migrations.CreateModel(
            name='ProductionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNo', models.PositiveIntegerField(default=1)),
                ('lineNo', models.CharField(default='0', max_length=4)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('salesOrder', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_components', to='Production.production')),
            ],
        ),
        migrations.CreateModel(
            name='ChildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='Production.billofmaterials')),
            ],
        ),
    ]
