# Generated by Django 4.2.8 on 2023-12-18 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_alter_employee_birth_date_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('leave_type', models.CharField(choices=[('casual_leave', 'Casual Leave'), ('medical_leave', 'Medical Leave')], default='casual_leave', max_length=20)),
                ('leave_duration', models.DurationField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=15)),
                ('id_no', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee')),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'employee')},
            },
        ),
    ]
