# Generated by Django 4.2.8 on 2023-12-18 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot_1', models.CharField(blank=True, max_length=255, null=True)),
                ('time_slot_2', models.CharField(blank=True, max_length=255, null=True)),
                ('time_slot_3', models.CharField(blank=True, max_length=255, null=True)),
                ('time_slot_4', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
