# Generated by Django 4.2.8 on 2023-12-18 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_arinvoiceinfo_arinvoiceitem'),
        ('Financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIncomeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_income_summary', to='Sales.salesorderinfo')),
            ],
            options={
                'verbose_name': 'Project Income Summary',
                'verbose_name_plural': 'Project Income Summaries',
            },
        ),
        migrations.CreateModel(
            name='ReceivedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='received_amount_images/')),
                ('project_income_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_amounts', to='Financials.projectincomesummary')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cost_images/')),
                ('project_income_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='Financials.projectincomesummary')),
            ],
        ),
    ]
