# Generated by Django 4.2.8 on 2023-12-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0002_projectincomesummary_receivedamount_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincomesummary',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projectincomesummary',
            name='total_received',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
