# Generated by Django 4.2.8 on 2023-12-16 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNo', models.PositiveIntegerField(default=1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('totalQty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('customerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartner.businesspartner')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('priceTotal', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('lineNo', models.PositiveIntegerField(default=0)),
                ('docNo', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchaseorderinfo')),
            ],
        ),
    ]
