# Generated by Django 4.2.8 on 2023-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0002_purchaseorderinfo_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quatationNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderinfo',
            name='quatationNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
