# Generated by Django 4.2.8 on 2023-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0005_apinvoiceinfo_apinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderinfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
    ]
