# Generated by Django 4.2.8 on 2023-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0003_projectbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projectbill',
            name='bill_type',
            field=models.CharField(choices=[('LABOUR', 'Labour Bill'), ('MATERIALS', 'Materials'), ('OTHERS', 'OTHERS')], default='LABOUR', max_length=10),
        ),
    ]
