# Generated by Django 4.2.8 on 2023-12-18 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManagement', '0005_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_amount_submitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.workflow')),
            ],
        ),
    ]
