# Generated by Django 4.2.8 on 2023-12-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessPartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1)),
                ('docNo', models.PositiveIntegerField(default=1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('totalQty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('edd', models.DateField(default=django.utils.timezone.now)),
                ('customerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartner.businesspartner')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Order',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('docNo', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('size', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('style', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('po', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('gweight', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nweight', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ctnno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('priceTotal', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('lineNo', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesorderinfo')),
            ],
        ),
    ]
